---
version: 2.0

jobs:
  stack-build:
    docker:
      - image: fpco/stack-build:lts-11.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
            - stack-{{ .Branch }}
            - stack-
      - run:
          name: Dependencies
          command: make setup
      - run:
          name: Build
          command: make build
      - save_cache:
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
  nix-build:
    docker:
      - image: nixos/nix:2.3
    steps:
      - checkout
      - run:
          name: Build
          command: nix-build
